server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhot:8761/eureka
    region: default
    registryFetchIntervalSeconds: 5
hystrix:
  command:
    reiseportal-author:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
zuul:
  routes:
    reiseportal-author:
      path: /reiseportal-discovery/**
      sensitive-headers: Set-Cookie, Authorization
    reiseportal-discovery:
      path: /reiseportal-discovery/**
      sensitive-headers: Set-Cookie, Authorization
      url: http://localhost:8082
spring:
  profiles:
    active: jdbc
  application:
    name: gateway
  cloud:
    config:
      name: gateway
      discovery:
        service-id: config
        enabled: true
      server:
        default-profile: production
        default-label: latest
        jdbc:
          sql: SELECT `key`, `value` FROM `properties` WHERE `application`=? AND `profile`=? AND `label`=?;
          order: 0
  jpa:
    hibernate.ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/reiseportal
    username: postgres
    password: secret